Lapr/updating project
nventive/Cartography pull request #1
Opened 2022-06-30 17:33 UTC by LProulx86

GitHub Issue: #

## Proposed Changes

 Prep for creating NuGet

## What is the current behavior?
Init of last map module.

## What is the new behavior?

## Checklist

Please check if your PR fulfills the following requirements:

- [x] Documentation has been added/updated (partial)
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [x] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [ ] Associated with an issue

## Other information

2022-06-30 18:55 UTC, carlh98 commented on Nventive.Location.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Nventive.Location", "Nventive.Location", "{6643A3E0-7CD4-4BCE-84BD-0B24B1720DC2}"
It should stay Cartography, we're not using Nventive.Location futhermore

2022-06-30 18:55 UTC, carlh98 commented on README.md
> +# Nventive.Location
Same

2022-06-30 18:58 UTC, carlh98 requested changes

2022-06-30 18:58 UTC, carlh98 commented on src/Nventive.Location/Nventive.Location.DynamicMap/Nventive.Location.DynamicMap.csproj
> +	  <ProjectReference Include="..\Nventive.Location.Core\Nventive.Location.Core.csproj" />
same

2022-06-30 19:15 UTC, LProulx86 commented on doc/MapService(umbrellaVersion).md
> +    1. Add a reference to the Umbrella Map Service (Umbrella.Location.MapService)
Yeap TODO that's why it's umbrellaVersion. (file name)

2022-07-04 17:36 UTC, carlh98 approved these changes

2022-07-04 17:37 UTC, merged